/* Generated By:JavaCC: Do not edit this line. parserP1Constants.java */
package uniandes.teolen.parserJavaCC.parserP1;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parserP1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int MODULO = 9;
  /** RegularExpression Id. */
  int IGUAL = 10;
  /** RegularExpression Id. */
  int MENOR = 11;
  /** RegularExpression Id. */
  int MAYOR = 12;
  /** RegularExpression Id. */
  int MENORIGUAL = 13;
  /** RegularExpression Id. */
  int MAYORIGUAL = 14;
  /** RegularExpression Id. */
  int DIFERENTE = 15;
  /** RegularExpression Id. */
  int NEGACION = 16;
  /** RegularExpression Id. */
  int AND = 17;
  /** RegularExpression Id. */
  int OR = 18;
  /** RegularExpression Id. */
  int INT = 19;
  /** RegularExpression Id. */
  int DIGIT = 20;
  /** RegularExpression Id. */
  int MAY = 21;
  /** RegularExpression Id. */
  int MIN = 22;
  /** RegularExpression Id. */
  int DEFINE = 23;
  /** RegularExpression Id. */
  int VAR = 24;
  /** RegularExpression Id. */
  int FUNCION = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"==\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"not\"",
    "\"and\"",
    "\"or\"",
    "<INT>",
    "<DIGIT>",
    "<MAY>",
    "<MIN>",
    "\"define\"",
    "<VAR>",
    "<FUNCION>",
    "\";\"",
  };

}
